### ISSUE TITLE
make clinical subset of mapping commons

### ISSUE THREAD

**Issue by mellybelly** [mapping-commons/mapping-commons.github.io#1]
For supporting the clinical communities, we need a mapping commons that is a subset of content that can be deployed in clinical systems. There are multiple strategies for achieving this - individual folders/repos/mappings could be tagged and therefore pulled into the server and systems. Alternatively we could have a secondary mapping commons that is where you put content that is focused on only clinically relevant mappings and terminologies/concept sets as defined by the their sources.  @callahantiff @chrisroederucdenver @matentzn @joeflack4

**Comment by joeflack4** [comment]
@mellybelly This is timely, in the context of the TermHub stuff that myself, @Sigfried, and @stephanieshong are doing. We've been thinking this week about where to put mappings. I kind of forgot you asked for this, but I made a [mirror issue](https://github.com/jhu-bids/TermHub/issues/166) in TermHub now.

@mellybelly @chrisroederucdenver I wouldn't mind spending TIMS time on this next week if it seems timely to work on.

## TermHub usage
Here's a snippet of some of the folders at the root of [TermHub](https://github.com/jhu-bids/TermHub):
<img width="269" alt="Screen Shot 2022-10-15 at 3 57 17 PM" src="https://user-images.githubusercontent.com/13045020/196005458-8aab783e-b914-4059-b2f3-1d263a88cf8f.png">

Those blue folders are `git submodule`s. We should probably do the same with mappings.
- [termhub-csets](https://github.com/jhu-bids/termhub-csets/tree/8bc3af0a3c9b783928f26ab7efe9ee640192669e)
- [termhub-vocab](https://github.com/jhu-bids/termhub-vocab/tree/a1a568eac094f4ee3ed947098de4bb10d8c98842)
- mapping-commons-mappings

## Steps
Here's some thoughts I have on breaking this down further.

### Integration/setup steps
- [ ] 1. Create 1 or more (potentially nested?) repos at mapping-commons.
- [ ] 2. TermHub: Use them as `git submodule`s when ready
- [ ] 3. TIMS: We can update [the loaders](https://github.com/HOT-Ecosystem/jpaserver-scripts) (@chrisroederucdenver just set this up on GitHub) to pull the content as well.

### Content steps
- [ ] 1. Categorize and store existing mappings (@mellybelly if you can link to some of this content, that'd be great. I know where the Mondo mappings are)
- [ ] 2. Make sure they're all in SSSOM
- [ ] 3. Convert to FHIR JSON
- [ ] 4. Eventually: Move to LinkML as central format, [similar to Enum/ValueSet work](https://github.com/linkml/linkml/pull/913)?

**Comment by chrisroederucdenver** [comment]
@mellybelly @joeflack4 I think we have incomplete and higher priority tickets open already.

**Comment by matentzn** [comment]
@joeflack4 can you mention this issue in our next 1:1? :) Thanks!

**Comment by matentzn** [comment]
This issue is afaics no longer important - we have the concept of decentralised registries now, and each registry can pool the mappings it would like!
