### ISSUE TITLE
Add recommended pronunciation to FAQ

### ISSUE THREAD

**Issue by DavidFichtmueller** [mapping-commons/mapping-commons.github.io#5]
I have come across many different pronunciation for SSSOM ("Tripple-Es Oh Em", "Es Es Es Oh Em", "Es Es Som" are more). This can sometimes cause some mild confusion, in particular when there is no written form accompanying the spoken words. During one of the discussions on how to properly pronounce the standard, I took a look at the FAQ, where I would have assumed to find a clarification on the topic but I didn't find any recommended pronunciation there. So I hereby suggest to add one. And for the time being I will stay with "Tripple-Es Oh Em" (analog to IIIF being called "Triple I Ef")until somebody suggest that there is a different and preferred pronunciation.

**Comment by matentzn** [comment]
@DavidFichtmueller I moved the discussion back to where you had it before! Thanks for reaching out:

https://github.com/mapping-commons/sssom/issues/352
